#! /home/garredondo_6/miniconda3/envs/bdnr/bin/python

import requests
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
my_db = client["swapi"]
list=["starships", "vehicles", "species", "films", "planets", "people"]

for table in list:
    collection = my_db[table]
    url = "https://swapi.py4e.com/api/"+table+"/"
    i = 1
    j = 1
    request = requests.get(url)
    response = request.json()
    limite = response["count"]
    #print(limite)
    res = []
    
    while j <= limite:
        url_i = url + str(i)
        req = requests.get(url_i)
        if req.status_code != 404:
            resp = req.json()
            res.append(resp)
            #print(j)
            j+=1
        i+=1
    print("fin de la tabla "+table)
    collection.insert_many(res)
print("fin de la inserción")
    
